### PR TITLE
:bug: Fix Scrolling is 'tripping' when at top or bottom when no-wrap …

### PR DESCRIPTION
**Pull request by SmallStoneDD**
…and itemCount is >= 5

### CODE REVIEW

**Comment by balazsbanyai** [comment]
This would be a critical fix for us. Is there a chance that it can be merged anytime soon?

**Comment by ShawnLin013** [comment]
@SmallStoneDD @balazsbanyai Could you provide any videos?

**Comment by ShawnLin013** [comment]
And this issue only can be reproduced by using this PR. 😅

**Comment by balazsbanyai** [comment]
The issue can be reproduced with the latest released version of this library, with **disabled wrapping** and **more than 5 i
tems**

The issue is _not_ reproducible using the code built from this PR.

This is how it looks: https://youtu.be/wo2hfMbrY5I

**Comment by shawn-lin-013** [comment]
Could you reproduce the issue on sample app? It would be better if you can paste the configs of number picker, such as java code or layout xml.

**Comment by ShawnLin013** [comment]
Could you reproduce the issue on sample app? It would be better if you can paste the configs of number picker, such as java code or layout xml.

**Comment by balazsbanyai** [comment]
Sure thing, this configuration reproduces the issue, here you go:
```
<com.shawnlin.numberpicker.NumberPicker
        android:id="@+id/horizontal_number_picker"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="60dp"
        app:np_orientation="horizontal"
        app:np_wrapSelectorWheel="false"
        app:np_min="16"
        app:np_max="32"
        app:np_maxFlingVelocityCoefficient="3"
        />
```

Video:
https://youtu.be/14q0ZtirocY

**Comment by ShawnLin013** [comment]
This PR only fixed the tripping in horizontal mode, but unfortunately it made the tripping in vertical mode. And this issue has been fixed at v2.4.11. @SmallStoneDD @balazsbanyai

**Pull request closed without merging**
